### ISSUE TITLE
configuring python3.9 on ubuntu to run this?

### ISSUE THREAD

**Issue by aspiringguru** [gitbls/imon#2]
my problem is possibly off topic but posting since I'm hoping resolving this problem will improve adoption of this package.

detailed description in SO link below, since SO provides better formatting and the likelihood my problem is not imon specific.
https://stackoverflow.com/questions/73888981/imon-bash-script-cant-see-python-package-installed-user-generated-bash-script

in short : ubuntu 20.04 has python 3.8 as standard. the /usr/local/bin/imon imports module icmplib and uses something else (my notes failed to record exactly what) requiring an upgrade from 3.8 to 3.9. I'm stuck with the weird behaviour of having a test bash script load python3.9 and import icmplib, while imon fails with an error 'module not found'.

maybe I've somehow created a weird non replicatable problem uneccessarily.

otherwise, package looks good, I feel it deserves broader adoption.

**Comment by gitbls** [comment]
Happy to hear that you find  imon interesting, but sorry you're having issues.

I'm guessing that when you installed icmplib you installed it using 'pip3 install icmplib` instead of `sudo pip3 install icmplib`. Without sudo it installs it only for your unprivileged user. If I'm correct, your test program will fail if you run it with sudo.

If re-installing icmplib with sudo doesn't resolve your issue, LMK and we can pursue further problem-solving. OTOH if it does resolve your issue, please report back here so others can benefit from your complete experience.

**Comment by aspiringguru** [comment]
thanks for the response.

I used 'python3.9 -m pip install icmplib' previously, apparently it gives better control on which python version receives the installed package.

after seeing your suggestion I uninstall the module, both locally and for root. then reinstalled the module.

now the only difference in sys.path between user and root is
 
'/home/m/f_projs/internet_monitor',  (in sys.path  when run as local user)
'/usr/local/bin', (in sys.path  when run as root)

neither of these directories have python packages in them.

**Comment by gitbls** [comment]
Packages installed with pip3 (or as you did) for the system are installed into /usr/local/lib/python3.9/dist-packages/

And that is apparently where python looks for them. This from my Bullseye system with Python 3.9.2 on it (from the distro), and by default the icmplib package ended up there.

Try this:
```
sudo find / -xdev -name '*icmplib*'
```
and you should see it in the directory mentioned above.

**Comment by gitbls** [comment]
Closing this since there has been no response/action on this from OP for a couple of months, Please feel free to reopen this issue, or start a new one, if you need additional assistance.

**Comment by gitbls** [comment]
Closing this since there has been no response/action on this from OP for a couple of months, Please feel free to reopen this issue, or start a new one, if you need additional assistance.
