### ISSUE TITLE
socket.gaierror icmplib.exceptions.NameLookupError when vpn is down

### ISSUE THREAD

**Issue by rsromanovskiy** [gitbls/imon#9]
i configure updown monitor and evrything is ok until vpn is down
:~/Python-3.9.9$ ~/ping_mos_stat.sh
 systemd[1]: Started imon Internet Monitor for instance ping_mos.
 imon[2481856]: imon [ping_mos] Starting
 imon[2481856]: imon [ping_mos] Version V2.97
 imon[2481856]: imon [ping_mos] Command line: /usr/local/bin/imon --instance ping_mos
 imon[2481856]: imon [ping_mos] Configuration file /etc/default/imon-ping_mos
 imon[2481856]: imon [ping_mos] ** [global] **
 imon[2481856]: imon [ping_mos]     action            /usr/local/bin/imon-action
 imon[2481856]: imon [ping_mos]     datefmt           %Y-%m-%d %H:%M:%S
 imon[2481856]: imon [ping_mos]     instance          ping_mos
 imon[2481856]: imon [ping_mos]     note
 imon[2481856]: imon [ping_mos]     imon-configure-version V1.0
 imon[2481856]: imon [ping_mos]     imon-configure-created 2024-10-22 12:33:08
 imon[2481856]: imon [ping_mos] ** [ddns] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          10
 imon[2481856]: imon [ping_mos]     pingcount         2
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos] ** [updown] **
 imon[2481856]: imon [ping_mos]     enable            True
 imon[2481856]: imon [ping_mos]     interval          3.0
 imon[2481856]: imon [ping_mos]     pingcount         3
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     monitorip         10.xx.xx.5
 imon[2481856]: imon [ping_mos]     addping           10.xx.xx.6,drive.xx.xx,192.168.1.1,xxx.xx
 imon[2481856]: imon [ping_mos]     dnsserver
 imon[2481856]: imon [ping_mos]     dnslookup
 imon[2481856]: imon [ping_mos] ** [failover] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          10
 imon[2481856]: imon [ping_mos]     pingcount         2
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     prefer-primary    False
 imon[2481856]: imon [ping_mos]     metric            201
 imon[2481856]: imon [ping_mos]     primary-if
 imon[2481856]: imon [ping_mos]     primary-name
 imon[2481856]: imon [ping_mos]     primary-gw
 imon[2481856]: imon [ping_mos]     primary-ping
 imon[2481856]: imon [ping_mos]     primary-postping
 imon[2481856]: imon [ping_mos]     standby-if
 imon[2481856]: imon [ping_mos]     standby-name
 imon[2481856]: imon [ping_mos]     standby-gw
 imon[2481856]: imon [ping_mos]     standby-ping
 imon[2481856]: imon [ping_mos]     standby-postping
 imon[2481856]: imon [ping_mos] ** [ping] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          1.0
 imon[2481856]: imon [ping_mos]     pingcount         3
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     monitorip         10.xx.xx.5
 systemd[1]: Started imon Internet Monitor for instance ping_mos.
 imon[2481856]: imon [ping_mos] Starting
 imon[2481856]: imon [ping_mos] Version V2.97
 imon[2481856]: imon [ping_mos] Command line: /usr/local/bin/imon --instance ping_mos
 imon[2481856]: imon [ping_mos] Configuration file /etc/default/imon-ping_mos
 imon[2481856]: imon [ping_mos] ** [global] **
 imon[2481856]: imon [ping_mos]     action            /usr/local/bin/imon-action
 imon[2481856]: imon [ping_mos]     datefmt           %Y-%m-%d %H:%M:%S
 imon[2481856]: imon [ping_mos]     instance          ping_mos
 imon[2481856]: imon [ping_mos]     note
 imon[2481856]: imon [ping_mos]     imon-configure-version V1.0
 imon[2481856]: imon [ping_mos]     imon-configure-created 2024-10-22 12:33:08
 imon[2481856]: imon [ping_mos] ** [ddns] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          10
 imon[2481856]: imon [ping_mos]     pingcount         2
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos] ** [updown] **
 imon[2481856]: imon [ping_mos]     enable            True
 imon[2481856]: imon [ping_mos]     interval          3.0
 imon[2481856]: imon [ping_mos]     pingcount         3
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     monitorip         10.xx.xx.5
 imon[2481856]: imon [ping_mos]     addping           10.xx.xx.6,drive.xxx.xxx,192.168.1.1,xx.xx
 imon[2481856]: imon [ping_mos]     dnsserver
 imon[2481856]: imon [ping_mos]     dnslookup
 imon[2481856]: imon [ping_mos] ** [failover] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          10
 imon[2481856]: imon [ping_mos]     pingcount         2
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     prefer-primary    False
 imon[2481856]: imon [ping_mos]     metric            201
 imon[2481856]: imon [ping_mos]     primary-if
 imon[2481856]: imon [ping_mos]     primary-name
 imon[2481856]: imon [ping_mos]     primary-gw
 imon[2481856]: imon [ping_mos]     primary-ping
 imon[2481856]: imon [ping_mos]     primary-postping
 imon[2481856]: imon [ping_mos]     standby-if
 imon[2481856]: imon [ping_mos]     standby-name
 imon[2481856]: imon [ping_mos]     standby-gw
 imon[2481856]: imon [ping_mos]     standby-ping
 imon[2481856]: imon [ping_mos]     standby-postping
 imon[2481856]: imon [ping_mos] ** [ping] **
 imon[2481856]: imon [ping_mos]     enable            False
 imon[2481856]: imon [ping_mos]     interval          1.0
 imon[2481856]: imon [ping_mos]     pingcount         3
 imon[2481856]: imon [ping_mos]     pingwait          1
 imon[2481856]: imon [ping_mos]     monitorip         10.xx.x.5
 imon[2481856]: imon [ping_mos] Start Updown Monitor for IP Address 10.x.x.5
 imon[2481856]: imon [ping_mos] Monitored IP 10.xx.xx.5 online
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.xx.6 offline
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.xx.84 online
 imon[2481856]: imon [ping_mos] Secondary IP 192.168.1.1 online
 imon[2481856]: imon [ping_mos] Secondary IP 5.xxx.xx.242 online
 imon[2481856]: imon [ping_mos] Monitored IP 10.xx.xx.5 offline
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.xx.6 offline
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.x.84 offline
 imon[2481856]: imon [ping_mos] Secondary IP 192.168.1.1 offline
 imon[2481856]: imon [ping_mos] Secondary IP 2a02:6b8::2:242 offline
 imon[2481856]: imon [ping_mos] Monitored IP 10.xx.xx.5 online
 imon[2481856]: imon [ping_mos] Outage Duration: 0 days 0 hours, 0 minutes 59 seconds
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.xx.6 offline
 imon[2481856]: imon [ping_mos] Secondary IP 10.xx.xx.84 online
 imon[2481856]: imon [ping_mos] Secondary IP 192.168.1.1 online
 imon[2481856]: imon [ping_mos] Secondary IP 77.88.44.242 online
 imon[2481856]: imon [ping_mos] Monitored IP 10.xx.xx.5 offline
 root[2563088]: imon action [ping_mos] updown-offline: updown-offline 10.xx.xx.5
 python[2481856]: Exception in thread Thread-1:
 python[2481856]: Traceback (most recent call last):
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/utils.py", line 158, in async_resolve
 python[2481856]:     lookup = await loop.getaddrinfo(
 python[2481856]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
 python[2481856]:     return await self.run_in_executor(
 python[2481856]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
 python[2481856]:     result = self.fn(*self.args, **self.kwargs)
 python[2481856]:   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
 python[2481856]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
 python[2481856]: socket.gaierror: [Errno -3] Temporary failure in name resolution
 python[2481856]: During handling of the above exception, another exception occurred:
 python[2481856]: Traceback (most recent call last):
 python[2481856]:   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
 python[2481856]:     self.run()
 python[2481856]:   File "/usr/local/bin/imon", line 330, in run
 python[2481856]:     self._reportdown()
 python[2481856]:   File "/usr/local/bin/imon", line 312, in _reportdown
 python[2481856]:     self._ckmonitoredips()
 python[2481856]:   File "/usr/local/bin/imon", line 288, in _ckmonitoredips
 python[2481856]:     hosts = multiping(addresses=self.pd.db['updown']['addping'], count=self.pd.db['updown']['pingcount'], timeout=self.pd.db['updown']>
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/multiping.py", line 267, in multiping
 python[2481856]:     return asyncio.run(
 python[2481856]:   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
 python[2481856]:     return loop.run_until_complete(main)
 python[2481856]:   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
 python[2481856]:     return future.result()
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in async_multiping
 python[2481856]:     return [task.result() for task in tasks]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in <listcomp>
 python[2481856]:     return [task.result() for task in tasks]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/ping.py", line 263, in async_ping
 python[2481856]:     address = (await async_resolve(address, family))[0]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/utils.py", line 168, in async_resolve
 python[2481856]:     return await async_resolve(name, 6)
 python[2481856]: icmplib.exceptions.NameLookupError: The name 'drive.xxx.xxxx' cannot be resolved

and i need to restart service 

sudo systemctl status imon@ping_mos
● imon@ping_mos.service - imon Internet Monitor for instance ping_mos
     Loaded: loaded (/etc/systemd/system/imon@.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-10-22 13:15:11 MSK; 1h 48min ago
   Main PID: 2481856 (python)
      Tasks: 1 (limit: 38001)
     Memory: 18.3M
        CPU: 2.010s
     CGroup: /system.slice/system-imon.slice/imon@ping_mos.service
             └─2481856 /root/.imon-venv/bin/python /usr/local/bin/imon --instance ping_mos

 python[2481856]:     return future.result()
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in async_multiping
 python[2481856]:     return [task.result() for task in tasks]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/multiping.py", line 163, in <listcomp>
 python[2481856]:     return [task.result() for task in tasks]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/ping.py", line 263, in async_ping
 python[2481856]:     address = (await async_resolve(address, family))[0]
 python[2481856]:   File "/root/.imon-venv/lib/python3.9/site-packages/icmplib/utils.py", line 168, in async_resolve
 python[2481856]:     return await async_resolve(name, 6)
 python[2481856]: icmplib.exceptions.NameLookupError: The name 'drive.xxx.xx' cannot be resolved
rromanovsky@NB-UBUNTU-12:~/Python-3.9.9$ sudo systemctl restart imon@ping_mos
rromanovsky@NB-UBUNTU-12:~/Python-3.9.9$ sudo systemctl status imon@ping_mos
● imon@ping_mos.service - imon Internet Monitor for instance ping_mos
     Loaded: loaded (/etc/systemd/system/imon@.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-10-22 15:04:28 MSK; 3s ago
   Main PID: 2610471 (python)
      Tasks: 4 (limit: 38001)
     Memory: 18.1M
        CPU: 338ms
     CGroup: /system.slice/system-imon.slice/imon@ping_mos.service
             └─2610471 /root/.imon-venv/bin/python /usr/local/bin/imon --instance ping_mos

 imon[2610471]: imon [ping_mos]     standby-ping
 imon[2610471]: imon [ping_mos]     standby-postping
 imon[2610471]: imon [ping_mos] ** [ping] **
 imon[2610471]: imon [ping_mos]     enable            False
 imon[2610471]: imon [ping_mos]     interval          1.0
 imon[2610471]: imon [ping_mos]     pingcount         3
 imon[2610471]: imon [ping_mos]     pingwait          1
 imon[2610471]: imon [ping_mos]     monitorip         10.xx.xx.5
 imon[2610471]: imon [ping_mos] Start Updown Monitor for IP Address 10.xx.xx.5
 imon[2610471]: imon [ping_mos] Monitored IP 10.xx.xx.5 online
rromanovsky@NB-UBUNTU-12:~/Python-3.9.9$ sudo systemctl status imon@ping_mos
● imon@ping_mos.service - imon Internet Monitor for instance ping_mos
     Loaded: loaded (/etc/systemd/system/imon@.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-10-22 15:04:28 MSK; 6s ago
   Main PID: 2610471 (python)
      Tasks: 2 (limit: 38001)
     Memory: 18.1M
        CPU: 345ms
     CGroup: /system.slice/system-imon.slice/imon@ping_mos.service
             └─2610471 /root/.imon-venv/bin/python /usr/local/bin/imon --instance ping_mos

imon[2610471]: imon [ping_mos]     interval          1.0
imon[2610471]: imon [ping_mos]     pingcount         3
imon[2610471]: imon [ping_mos]     pingwait          1
imon[2610471]: imon [ping_mos]     monitorip         10.xx.xx.5
imon[2610471]: imon [ping_mos] Start Updown Monitor for IP Address 10.xx.xx.5
imon[2610471]: imon [ping_mos] Monitored IP 10.xx.xxx.5 online
imon[2610471]: imon [ping_mos] Secondary IP 10.xx.xxx.6 offline
imon[2610471]: imon [ping_mos] Secondary IP 10.xx.x.84 online
imon[2610471]: imon [ping_mos] Secondary IP 192.168.1.1 online
imon[2610471]: imon [ping_mos] Secondary IP 5.xxx.xx.242 online

**Comment by gitbls** [comment]
Sorry you're having an issue.

I won't be able to look at this for several days, but before I get around to it, I'll need you to:
* Format the output so that it's more readable using code tags (surround code with 3 backticks) so that it uses a fixed-width font. It's completely illegible to me as is
* Explain your network configuratiion
  * What VPN?
  * What IP addresses are related to the VPN?
  * etc
* Please don't obfuscate local IP addresses (192.168... and 10.xxx). Those have no meaning outside of your network and it simply makes it more difficult to interpret what's going on

Also, please be aware that I've not tested imon AT ALL with respect to monitoring a VPN, so you are in completely uncharted territory. Depending on the VPN you're using, it may not be possible for imon to do what you are trying to do with it, but I'll know more once you update per the above and I have an opportunity to review it in detail.

**Comment by rsromanovskiy** [comment]
vpn - some like openvpn with proprietary encryption.from my company. 
192.xxxx its my router
10.xx its network relataed to vpn
drive.xxx dns name of server at vpn network
xxx its requirements from company - local address is too
another ip - seach server in internet(like google)

when vpn is down directly(device tun0 is out, and route changed), no error.
i think, it after hibernate, or standby mode 
may be imon send packet to null device.

**Comment by gitbls** [comment]
Please download and try the latest imon. The only file changed is `imon` itself. This logs the DNS Name Lookup Error but continues instead of committing hari-kari.

Please LMK if this resolves your issue.

**Comment by rsromanovskiy** [comment]
Thanks. now if up down restart vpn imon work correct.
![Screenshot from 2024-11-01 14-53-33](https://github.com/user-attachments/assets/28eaf9dd-3ae3-41ea-b0df-bcf55f1574bc)

**Comment by gitbls** [comment]
Thanks for confirming.
